---

- name: "Build font container with ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop front_container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm front_container
    ignore_errors: yes
    

  - name: remove used image
    command: docker rmi front_achat
    ignore_errors: yes
    

  - name: build docker image from dockerfile
    command: docker build -t front_achat .

  - name: run container from image
    command: docker run -d --name front_container -p 8087:8087 front_achat

  - name : test
    command: ls 
