---

- name: "Build font container with ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop front-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm front-container
    ignore_errors: yes
    

  - name: remove used image
    command: docker rmi front-achat
    ignore_errors: yes
    

  - name: build docker image from dockerfile
    command: docker build -t front-achat .

  - name: run container from image
    command: docker run -d --name front-container -p 8087:8087 front-achat

  - name : test
    command: ls 
